#!/usr/bin/env bash

# Small delay to allow session initialization
sleep 0.5

### DBUS
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

### CURSOR
xsetroot -cursor_name left_ptr &

### HOTKEY
pgrep -x sxhkd >/dev/null || sxhkd &

### WALLPAPER
pgrep -x feh >/dev/null || \
feh --no-fehbg --bg-fill "$HOME/.config/bspwm/wallpaper/wallpaper4.png" &

### NOTIFICATION
pgrep -x dunst >/dev/null || dunst &

### POLKIT
pgrep -x polkit-gnome-authentication-agent-1 >/dev/null || \
/usr/libexec/polkit-gnome-authentication-agent-1 &

### AUDIO
(
sleep 1
pkill -x wireplumber 2>/dev/null
pkill -x pipewire-pulse 2>/dev/null
pkill -x pipewire 2>/dev/null
sleep 0.5
pipewire &
pipewire-pulse &
wireplumber &
) &

### COMPOSITOR
pgrep -x picom >/dev/null || ~/.config/picom/auto.sh &

### BAR
pgrep -x polybar >/dev/null || ~/.config/polybar/launch.sh &

### MONITOR HOTPLUG
pgrep -f monitor >/dev/null || ~/.config/sxhkd/scripts/monitor &
